In [6]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [23]:

def least_squares(y, tx):
    #print (y,tx)
    xtx=np.dot(tx.T,tx)
       #print(xtx)
    xtx=np.linalg.inv(xtx)
    #print(xtx)
    w=np.dot(xtx,np.dot(tx.T,y))
    return w

In [24]:
#least_squares(np.array([3,4]),np.array([[1,1],[0,1]]))



[3 4] [[1 1]
 [0 1]]
[[1 1]
 [1 2]]
[[ 2. -1.]
 [-1.  1.]]


array([-1.,  4.])

array([-1, 10])